sunshine/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'sunshine'

urlpatterns = [
    path('home',views.home ,name='home'),
     path('',views.index , name='index'),
     path('blogs',views.blogs, name='blogs'),
     path('post',views.post, name='post'),
     path('media',views.media, name='media')
]   

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sunshinev/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sunshine.urls')),
]

sunshine/models.py
from django.db import models
from datetime import date
from datetime import datetime
import datetime
from django.template.defaultfilters import slugify


class Carousel(models.Model):
    title = models.CharField(max_length=30)
    body = models.CharField(max_length=100)
    image = models.ImageField(null=True, upload_to="media/carousels")
    slug = models.SlugField(null=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.title

class Event(models.Model):
    eventname = models.CharField(max_length=100)
    date = models.DateField(default=date.today)
    image = models.ImageField(null=True, upload_to="media/events")
    eventinfo = models.TextField(max_length=850,null=True)
    coodinator = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)
    
    @property
    def image_url(self):
        if self.image (self.image, 'url'):
            return self.image.url

    def __str__(self):
        return self.eventname

    @property
    def today_event(self):
        tday = date.today()
        return  tday

class Head(models.Model):
    leader = models.CharField(max_length=70,null=True)
    department = models.CharField(max_length=100)
    phone_number = models.IntegerField(null=True)
    images = models.ImageField(null=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.leader

class Ministries(models.Model):
    ministry = models.CharField(max_length=40)
    leader = models.CharField(max_length=70,null=True)
    goals = models.CharField(max_length=80)
    mission = models.CharField(max_length=80)
    vision = models.CharField(max_length=80)
    images = models.ImageField(null=True)
    contacts = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)


    def __str__(self):
        return self.ministry

class Blog(models.Model):
    title = models.CharField(max_length=64,unique=True)
    author = models.CharField(max_length=32)
    images = models.ImageField(null=True)
    content = models.TextField()
    category = models.ForeignKey('sunshine.Category',on_delete=models.CASCADE,null=True)
    slug = models.SlugField(max_length=128,null=True,unique=True)
    updated_on = models.DateField(auto_now=True)
    created_on = models.DateField(auto_now_add=True)
    publish_on = models.DateField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.headline)
        super(Blog, self).save(*args, **kwargs)
    

class Category(models.Model):
   title = models.CharField(max_length=100, db_index=True)


class Media(models.Model):
    Video = models.FileField (max_length=254)
    Audio = models.FileField (max_length=254,null=True)
    image = models.ImageField(null=True)

sunshine/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Carousel,Event,Ministries,Head,Blog,Media


def home(request) :
    carousel = Carousel.objects.all()
    events = Event.objects.all()
    
    context = {
         "events" : events,
         "carousel" : carousel,
    }

    return render(request, 'sunshine/home.html',context)


def index(request) :
    ministries = Ministries.objects.all()[:6]
    head = Head.objects.all()
    events = Event.objects.all()[:2]

    context = {
         "ministries" : ministries,
         "head" : head,
         "events" : events
    }

    return render(request, 'sunshine/index.html',context)

def blogs(request):
     blog = Blog.objects.all()#(blog,lookup=slug)
     
     context ={
          "blog" : blog
     }

     return render(request, 'sunshine/blogs.html',context)

def post(request):
     blog = Blog.objects.all()[:1]
     
     context ={
          "blog" : blog
     }

     return render(request, 'sunshine/post.html', context)

def media(request):
     media = Media.objects.all()

     context ={
          "media" : media
     }

     return render(request,'sunshine/media.html')

def fetch(request):
    if request.method == 'GET':
        media = request.GET['media']
        return HttpResponse('success')
    else:
        return HttpResponse("unsuccesful")

sunshine/templates/sunshine/base.html
{% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Yasham Foundation</title>
      <!-- CSS -->
      <link href="css/custom.css" rel="stylesheet">

      <!-- Font Awesome -->
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
      <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
       {% block links %}

       {% endblock links %}
    </head>
  
 
    <!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
	<div class="container-fluid">
		<a class="navbar-logo" href="#" src="img/logo.ng"></a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">

        <a class="nav-link" href="{% url 'sunshine:home' %}">HOME<span class="sr-only">(current)</span></a>
      </li>
      <li>
        <a class="nav-link" href="{% url 'sunshine:ministries' %}">VOLUNTEERS</a>
      </li>
      <li>
        <a class="nav-link" href="{% url 'sunshine:resources' %}">RESOURCES</a>
      </li>
      <li>
        <a class="nav-link" href="{% url 'sunshine:connect' %}">JOIN US</a>
      </li>
  </div>
		</button>
	</div>
</nav>
    

  
</nav>
</div>

{% block content %}
{% endblock %}

<!-- FOOTER -->

<!-- Footer -->
<footer class="page-footer font-small blue pt-4 ">
  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Contact us</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Totam earum ad optio vero quia. Quis nam blanditiis dignissimos sapiente dolor veritatis non nihil, saepe praesentium ratione facere eum illum? Eligendi!</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">
      
      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">connect with us</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">facebook</a>
          </li>
          <li>
            <a href="#!">twitter</a>
          </li>
          <li>
            <a href="#!">Instagram</a>
          </li>
        </ul>
        
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Hours of service</h5>
        6-7pm<br>
        ec etc

        

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
</footer>
<!-- Footer -->
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; Yasham NGO &middot; <a href="#"></a></p>
  </footer>
</main>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>


    

    <!-- Optional JavaScript -->
  

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block script%}
    
    {% endblock script %}
  </body>
</html>

sunshine/templates/sunshine/blogs.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Sunshine Blogs</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'sunshine:index' %}">Yasham Foundation</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sunshine:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sunshine:blogs' %}">Blogs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sunshine:media' %}">Media</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static "img/header-bg.jpg" %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Blogs and News</h1>
            <span class="subheading"> Welcome to our blogs and upcoming events </span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  {% for blog in blog %}

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">

          
          <a href="{% url 'sunshine:post' %}">
            <h2 class="post-title">
              {{blog.title}}
            </h2>
            <h3 class="post-subtitle">
              {{blog.slug}}
            </h3>
          </a>
          <p class="post-meta">written by
            <a href="#">{{blog.author}}</a>
            on {{blog.publish_on}}</p>
          
            
        </div>
        
        <hr>
        <!-- Pager -->
        
        
      </div>
      
    </div>
    
  </div>

  {% endfor %}

  <div class="clearfix">
    <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
  </div>
 
  


   
  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

sunshine/templates/sunshine/media.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Media</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'sunshine:index' %}">Yasham Foundation</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sunshine:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sunshine:blogs' %}">Blogs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sunshine:media' %}">Media</a>
        </ul>
      </div>
    </div>
  </nav>
  

  
  <!-- Page Header -->
  <header class="masthead" style="background-image: url({% static "img/media.jpg" %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>hello,</h1>
            <h2 class="subheading">welcome to our gallery</h2>
            <p class="post-meta">
                <a href="#"></a>
                </p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
 <!-- Page Content -->
 <div class="container">

    <div class="row">

      <div class="col-lg-3">

        <h1 class="my-4">Shop Name</h1>
        <div class="list-group">
          <a href="#get" id="get"  class="list-group-item">Video</a>
          <a href="#" class="list-group-item">Audios</a>
          <a href="#" class="list-group-item">Picture gallery</a>
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

       

        <div class="row">

          <div class="col-lg-5 col-md-6 mb-4">
            <div class="card h-300">
              <a href=""><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="#">Item One</a>
                </h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
              </div>
            </div>
          </div>

        </div>
        <!-- /.row -->

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Yasham 2010</p>
        </div>
      </div>
    </div>
  </footer>

  <script type="text/javascript">

    $('.view').click(function(){ 
    var id; 
    id = $(this).attr("data-catid"); 
    $.ajax( 
      
    { 
        type:"GET", 
        url: "media", 
        data:{ 
                 media : id 
    }, 
    success: function( data ) 
    { 
       } }) });

  </script>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
  <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>

sunshine/templates/sunshine/post.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Clean Blog - Start Bootstrap Theme</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'sunshine:index' %}">Yasham Foundation</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sunshine:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sunshine:index' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sunshine:blogs' %}">Blogs</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  

  {% for blog in blog %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url({{ blog.images.url }})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>{{blog.title}}</h1>
            <h2 class="subheading">{{blog.category}}</h2>
            <p class="post-meta">written by
                <a href="#">{{blog.author}}</a>
                on {{blog.publish_on}}</p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          {{blog.content}}
        </div>
      </div>
    </div>
  </article>
  {% endfor %}
  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Sunshine 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>

</html>